export interface EnrollmentInterface {
  code: string;
  firstName: string;
  lastName: string;
  sex: string;
  dob: string;
  nationality: string;
  telegram: string;
  fatherName: string;
  motherName: string;
  education: string;
  bacIIGrade: string;
  bacIICertificateCode: string;
  bacIIYear: number;
  highSchoolName: string;
  highSchoolLocation: string;
  careerType: string;
  academicUnit: string;
  country: string;
  province: string;
  district: string;
  commune: string;
  village: string;
  phoneNumber: string;
  guardianNumber: string;
  emergencyName: string;
  relationship: string;
  emergencyContact: string;
  emergencyWorkplace: string;
  majorId: number;
  registerDate: string;
  registerType: string;
  status: string;
  batch: string;
}

export const defaultEnrollment: EnrollmentInterface = {
  code: "",
  firstName: "",
  lastName: "",
  sex: "",
  dob: "",
  nationality: "",
  telegram: "",
  fatherName: "",
  motherName: "",
  education: "",
  bacIIGrade: "",
  bacIICertificateCode: "",
  bacIIYear: 0,
  highSchoolName: "",
  highSchoolLocation: "",
  careerType: "",
  academicUnit: "",
  country: "",
  province: "",
  district: "",
  commune: "",
  village: "",
  phoneNumber: "",
  guardianNumber: "",
  emergencyName: "",
  relationship: "",
  emergencyContact: "",
  emergencyWorkplace: "",
  majorId: 0,
  registerDate: "",
  registerType: "",
  status: "",
  batch: "",
};
